services:
    loki:
        image: grafana/loki
        container_name: loki
        hostname: loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./loki-config:/etc/loki/
        restart: always
        networks:
            - world
            - grafana-loki
            - promtail-loki

    promtail:
        depends_on:
            - loki
        image: grafana/promtail
        container_name: promtail
        hostname: promtail
        networks:
            - promtail-loki

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        ports:
            - "9090:9090"
        networks:
            - world
            - grafana-prometheus
        
    grafana:
        depends_on:
            - loki
        image: grafana/grafana-oss
        container_name: grafana
        hostname: grafana
        environment:
            # increases the log level from info to debug
            - GF_LOG_LEVEL=debug
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - grafana-data:/var/lib/grafana
        ports:
            - "3000:3000"
        networks:
            - world
            - grafana-loki
            - grafana-prometheus
volumes:
  grafana-data:
  
networks:
    world:
    promtail-loki:
        internal: true
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true